export const dev = window.location.origin.includes('localhost')
export const baseURL = dev ? 'http://localhost:3000' : ''
export const useSockets = false
export const domain = 'codeworksstudent2002.us.auth0.com'
export const clientId = 'FJSxOpdo6j22yoYepRnRq1xgiE5u9n81'
export const audience = 'https://codingisamazing.com'
// export const domain = 'codeworksstudent2002.us.auth0.com'
// export const clientId = 'FJSxOpdo6j22yoYepRnRq1xgiE5u9n81'
// export const audience = 'https://codingisamazing.com'
